version: 1.0.{build}

platform:
  - x64

configuration:
  - Release

environment:
  toolset: v140

install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan==1.18.5 --quiet
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: cd %APPVEYOR_BUILD_FOLDER%/conan-recipes
  - cmd: conan create conan-libyaml user/testing -s build_type=%CONFIGURATION% -s compiler.toolset=%toolset%
  - cmd: conan create conan-gtest-1.8.1 user/testing -s build_type=%CONFIGURATION% -s compiler.toolset=%toolset%
  - cmd: conan create conan-vxl-v1.18.0 user/testing -s build_type=%CONFIGURATION% -s compiler.toolset=%toolset%

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: cd conan-recipe-tomato
  - cmd: conan create -s build_type=Release . test/production
  - cmd: conan create -s build_type=Debug . test/production
  - cmd: mkdir build
  - cmd: conan install . #-o gtest:shared=True
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 14 2015 Win64"
  - cmd: cmake --build . --config Release

test_script:
  - cmd: cd bin
  - cmd: TomatoExe.exe
